#!/bin/bash

echo ">>${MCMI_CA_KEY}<<"
echo ">>${MCMI_CA_CERT}<<"
echo ">>${MCMI_KEY}<<"
echo ">>${MCMI_CERT}<<"

docker build \
    --build-arg MCMI_VERSION="${DOCKER_TAG}" \
    --build-arg MCMI_CA_KEY \
    --build-arg MCMI_CA_CERT \
    --build-arg MCMI_KEY \
    --build-arg MCMI_CERT \
    --file "$DOCKERFILE_PATH" \
    --tag "$IMAGE_NAME" .
