#!/bin/bash

docker build \
    --build-arg ZIMAGI_VERSION="${DOCKER_TAG}" \
    --build-arg ZIMAGI_CA_KEY \
    --build-arg ZIMAGI_CA_CERT \
    --build-arg ZIMAGI_KEY \
    --build-arg ZIMAGI_CERT \
    --file "$DOCKERFILE_PATH" \
    --tag "$IMAGE_NAME" .
